# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: maven:3.5.3-jdk-8-alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/circleci-demo-java-spring

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn test
  docker-build:
    docker:
      - image: docker
    working_directory: ~/circleci-demo-java-spring-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t victorszewczenko/circleci-demo-docker:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push victorszewczenko/circleci-demo-docker:$TAG

workflows:
      version: 2
      build-master:
        jobs:
          - build:
          - docker-build:
              requires:
                - build
              filters:
                branches:
                  only: master
