version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: maven:3.5.3-jdk-8-alpine

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/circleci-demo-java-spring

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - circleci-demo-java-spring-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn test
  sonarqube:
    docker:
      # specify the version you desire here
      - image: maven:3.5.3-jdk-8-alpine
    working_directory: ~/circleci-demo-java-spring-sonarqube
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - circleci-demo-java-spring-sonarqube-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-sonarqube-{{ checksum "pom.xml" }}

      # run tests!
      - run: |
         mvn clean
         mvn package \
                -Dmaven.test.skip=true \
            org.jacoco:jacoco-maven-plugin:prepare-agent \
            sonar:sonar \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.projectKey=circleci-integration \
                -Dsonar.login=$SONAR_AUTH_TOKEN \
                -Dsonar.exclusions=srcgen/**/*
  docker-build:
    docker:
      - image: docker
    working_directory: ~/circleci-demo-java-spring-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t victorszewczenko/circleci-demo-docker:$TAG .     
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push victorszewczenko/circleci-demo-docker:$TAG
workflows:
  version: 2
  build-master:
    jobs:
      - test
      - sonarqube:
          filters:
            branches:
              only: master
      - docker-build:
          requires:
            - test
            - sonarqube
          filters:
            branches:
              only: master
